apiVersion: v1
kind: ConfigMap
metadata:
  name: ecommerce-config
  namespace: ecommerce
data:
  # Backend configuration
  PORT: "5000"
  NODE_ENV: "production"

  # Database configuration
  DB_HOST: "postgres-service"
  DB_PORT: "5432"
  DB_NAME: "ecommerce"

  # Prometheus configuration
  PROMETHEUS_URL: "http://prometheus-service:9090"

  # Grafana configuration
  GF_SECURITY_ADMIN_USER: "admin"
