apiVersion: v1
kind: Secret
metadata:
  name: ecommerce-secrets
  namespace: ecommerce
type: Opaque
stringData:
  # PostgreSQL credentials
  DB_USER: "devops"
  DB_PASSWORD: "devops123"
  POSTGRES_USER: "devops"
  POSTGRES_PASSWORD: "devops123"
  POSTGRES_DB: "ecommerce"

  # Grafana admin password
  GF_SECURITY_ADMIN_PASSWORD: "admin123"

  # PostgreSQL connection string for postgres-exporter
  DATA_SOURCE_NAME: "postgresql://devops:devops123@postgres-service:5432/ecommerce?sslmode=disable"
